package:
  name: docker-client
  version: 27.0.1
  epoch: 0
  description: "Docker client binary - excludes container runtime"
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: 'Copyright 2013-2018 Docker, Inc.'
      license: 'Apache License, Version 2.0'
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://download.docker.com/linux/static/stable/x86_64/docker-${{package.version}}.tgz
      expected-sha256: 1e65f8bd3ac5ba8a4267a680a5427b59f8af1c1a3853bdbf77cdcaa33d5f6504
      strip-components: 0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      cp docker/docker ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  release-monitor:
    identifier: 11719 # https://release-monitoring.org/project/11719/
