package:
  name: docker-client
  version: 29.4.3
  epoch: 0
  description: "Docker client binary - excludes container runtime"
  target-architecture:
    - x86_64
  copyright:
    - paths:
        - "*"
      attestation: 'Copyright 2013-2018 Docker, Inc.'
      license: 'Apache License, Version 2.0'
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: fetch
    with:
      uri: https://download.docker.com/linux/static/stable/x86_64/docker-${{package.version}}.tgz
      expected-sha256: bc9734a89d3edd15eeca8620961f6499ba69948814c85d7ac3488e34b3e16d01
      strip-components: 0

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      cp docker/docker ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  release-monitor:
    identifier: 11719 # https://release-monitoring.org/project/11719/
